[colors]
foreground    = "#c0caf5"
background    = "#1a1b26"
cursor_fg     = "#1a1b26"
cursor_bg     = "#ced6f7"
cursor_border = "#222330"
selection_fg  = "#9394aa"
selection_bg  = "#2c4075"
ansi = ["#65677d", "#292223", "#252329", "#252322", "#6e20bd", "#bb9bf7", "#c0caf5", "#FFFFFF"]
brights = ["#ffa500", "#ff0000", "#9394aa", "#ffa500", "#b38df6", "#98abef", "#9394aa", "#FFFFFF"]
