[colors]
foreground    = "#b4bdc3"
background    = "#1c1917"
cursor_fg     = "#1c1917"
cursor_bg     = "#c4cacf"
cursor_border = "#25211f"
selection_fg  = "#a1938c"
selection_bg  = "#3d4042"
ansi = ["#6e6763", "#272020", "#252024", "#242120", "#65435e", "#b4bdc3", "#b4bdc3", "#FFFFFF"]
brights = ["#ffa500", "#ff0000", "#a1938c", "#ffa500", "#bf8fb5", "#979fa4", "#a1938c", "#FFFFFF"]
