[colors]
foreground    = "#c8d3f5"
background    = "#222436"
cursor_fg     = "#222436"
cursor_bg     = "#c8d3f5"
cursor_border = "#2f334d"
selection_fg  = "#86e1fc"
selection_bg  = "#2d3f76"
ansi = ["#1b1d2b", "#ff757f", "#c3e88d", "#ffc777", "#82aaff", "#c099ff", "#86e1fc", "#FFFFFF"]
brights = ["#ffc777", "#c53b53", "#86e1fc", "#ffc777", "#ff966c", "#c099ff", "#86e1fc", "#FFFFFF"]
