# packages = ["appdata"]

[nvim.files]
nvim = "~/AppData/Local/nvim"


[wallomizer.files]
wallomizer = "~/.local/bin"

[appdata.files]
appdata = "~/AppData/Roaming/"

[nushell.files]
nushell = "~/AppData/Roaming/nushell"
